# MPSE cost

In [1]:
import sys; sys.path.insert(0,"../")
import numpy as np

import mview

Here we go over how to compute MPSE costs and individual costs for a set of distances/dissimilarities and a candidate pair of embedding and projection parameters.

The data used for this example is below:

In [2]:
N = 4 #number of points
X = np.random.randn(N,3) #positions in 3D
Q = mview.projections.PROJ().generate(number=3,method='standard') #list with projection arrays

print('embedding:')
print(X)

print('projections:')
for q in Q:
    print(q) #projection
    
Y = mview.projections.PROJ().project(Q,X)

print('images:')
for y in Y:
    print(y) #images

from scipy.spatial import distance_matrix
D = []
for y in Y:
    D.append(distance_matrix(y,y))

print('distance matrices:')
for d in D:
    print(d) #distances

embedding:
[[ 0.28979389 -0.38231124  0.09648515]
 [-0.07017929  1.11091152  0.2896217 ]
 [ 1.28503085 -1.0137629  -0.71479559]
 [-0.84004353  0.82693493  0.47862131]]
projections:
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]]
images:
[[ 0.28979389 -0.38231124]
 [-0.07017929  1.11091152]
 [ 1.28503085 -1.0137629 ]
 [-0.84004353  0.82693493]]
[[ 0.28979389  0.09648515]
 [-0.07017929  0.2896217 ]
 [ 1.28503085 -0.71479559]
 [-0.84004353  0.47862131]]
[[-0.38231124  0.09648515]
 [ 1.11091152  0.2896217 ]
 [-1.0137629  -0.71479559]
 [ 0.82693493  0.47862131]]
distance matrices:
[[0.         1.53599965 1.17865509 1.65493471]
 [1.53599965 0.         2.5200865  0.8205691 ]
 [1.17865509 2.5200865  0.         2.81142484]
 [1.65493471 0.8205691  2.81142484 0.        ]]
[[0.         0.40851244 1.28400664 1.19271146]
 [0.40851244 0.         1.68684576 0.79272429]
 [1.28400664 1.68684576 0.         2.43724948]
 [1.19271146 0.79272429 2.43724948 0.        ]]
[[0.        

To compute the cost and individual costs in MPSE using D as the true data and X and Q as the embedding and projections, we run the following:

In [3]:
mv = mview.MPSE(D,initial_embedding=X,initial_projections=Q)
print('total cost:',mv.cost)
print('individual costs:',mv.individual_cost)

total cost: 0.0
individual costs: [0. 0. 0.]


If we perturb the embedding and projections, we move away from a total cost of 0, as expected.

In [4]:
def add_noise(epsilon):
    X0 = X+epsilon*np.random.randn(N,3)
    Q0 = []
    for q in Q:
         Q0.append(q+epsilon*np.random.randn(2,3))
    mv = mview.MPSE(D,initial_embedding=X0,initial_projections=Q0)
    print(f'{epsilon:0.2e}, {mv.cost:0.2e}', mv.individual_cost)

for epsilon in 10**np.arange(-4,0,.5):
    add_noise(epsilon)

1.00e-04, 1.24e-04 [1.34543018e-04 6.29276811e-05 1.55585309e-04]
3.16e-04, 6.30e-04 [0.00053031 0.00044225 0.00084533]
1.00e-03, 2.17e-03 [0.00246422 0.00210086 0.001922  ]
3.16e-03, 8.04e-03 [0.00602195 0.00644122 0.01076717]
1.00e-02, 1.56e-02 [0.01383523 0.0192225  0.01292659]
3.16e-02, 6.31e-02 [0.05124139 0.04201499 0.08698767]
1.00e-01, 4.08e-01 [0.20800961 0.59648617 0.31507368]
3.16e-01, 1.09e+00 [1.12938968 0.70833614 1.32527315]
